Cloud testapp
Otus-DevOps-2022-11/nosko-stojachkov_infra pull request #3
Opened 2022-12-21 09:55 UTC by nosko-stojachkov

# Выполнено ДЗ № 6

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Пункт 1
 - Пункт 2

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2022-12-21 13:55 UTC, nosko-stojachkov commented
@mrgreyves, у меня не проходит проверка.
Я понимаю, что не удаётся выполнить команды:
sudo systemctl enable mongod
sudo systemctl start mongod
или
sudo service mongod start 
и тп.
Как это исправить?

2022-12-22 09:37 UTC, mrgreyves requested changes
Здравствуйте!)
Когда вы все настраиваете, у вас все работает?
Видно что приложение работает не корректно, не удается добавить пост в сервис
Кажется что вам не удалось установить монгу и добиться работоспобности приложения
Если какие то доп вопросы, задавайте =)

2022-12-22 10:51 UTC, nosko-stojachkov commented
@mrgreyves 
> Здравствуйте!) Когда вы все настраиваете, у вас все работает? Видно что приложение работает не корректно, не удается добавить пост в сервис Кажется что вам не удалось установить монгу и добиться работоспобности приложения Если какие то доп вопросы, задавайте =)

При ручной установке инстанса и установки приложений проблем не возникает.
Если вы посмотрите лог то увидите, что Mongo установлена, но запустить её не получается.
Такие команды, как systemctl start mongod или service mongod start не отрабатывают.

![image](https://user-images.githubusercontent.com/59222541/209118033-c2e22f70-b540-44fc-ab6c-8c10ac3095b2.png)

2022-12-25 21:39 UTC, mrgreyves approved these changes
Здравствуйте!)
Вот сейчас уже все корректно
С монгой вцелом проблемы сейчас =(
Можно дополнительно перепроверить и попробовать mongod
Имя пакета может быть изменено =)

2022-12-26 06:03 UTC, merged